### ISSUE TITLE
Cant send POST data through websocket

### ISSUE THREAD

**Issue by antholord** [mehmetkose/react-websocket#16]
I need to send an array of simple objects to the websocket, and as far as I know this is not possible since the websocket url is GET only.

Is there a way I'm missing to send more complex params through the URL or would it be a potential feature to add?

**Comment by mehmetkose** [comment]
POST, GET, PUT is **http** things. Websocket (ws://) is totally different prothocol. So it's not possible. You can send or get string through websocket.

**Comment by mehmetkose** [comment]
may socket.io do this. I dunno, better you check though..
