### ISSUE TITLE
onClose is not being fired

### ISSUE THREAD

**Issue by awb99** [mehmetkose/react-websocket#23]
I am not getting onClose events via WebSocket. onOpen events work fine. I have built a test websocket server via node.js that I am starting and stopping.

```
 <Websocket url='ws://localhost:3132/btc/' 
             debug={true}
             protocol="echo-protocol"  
             onMessage={this.handleData.bind(this)}
             reconnect={true}
             onClose={this.handleClose.bind(this)}
             onOpen={this.handleOpen.bind(this)}
        />
```
Console printout:
```
bundle.js:103859 WebSocket connection to 'ws://localhost:3132/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ bundle.js:103859
bundle.js:103825 Websocket disconnected
```
I did a npm install today, and am using the redux-minimal.js.org starter kit.

I think this is a bug.

**Comment by masche842** [comment]
It's in the index.jsx file, but not yet in build/index.js.
Workaround is to clone the repo, run "npm install && npm run prerelease".
Long term solution is to commit the result (after testing).

**Comment by antonlindgren** [comment]
Is there a fix coming or is the solution @masche842 suggested the way to go?

**Comment by stevanus1997** [comment]
dude that onClose still not working :(
