### ISSUE TITLE
How to send?

### ISSUE THREAD

**Issue by ghost** [mehmetkose/react-websocket#4]
How do you reference the websocket to send and control?
thx

**Comment by mehmetkose** [comment]
check this code. there is not any listenning method yet. the component just for listen

**Comment by mehmetkose** [comment]
@ahmadster Hello again. I'm mainteiner now. So, I'll add this future soon.

**Comment by whitebook** [comment]
Any progress on this issue...

Thanks.

**Comment by mehmetkose** [comment]
unfortunatelly, I didnt added yet. but contributions are welcome.

**Comment by pimvoeten** [comment]
What do you mean by 'not added yet'? Do I need to do something for you?

**Comment by mehmetkose** [comment]
Im working on it

**Comment by dmrz** [comment]
Hello. I am new to React world so I am curious why there is a need for some extra work, when you can just use ref callback attribute to access Websocket component instance from the one you are going to send? Is it a bad idea?

**Comment by tobez** [comment]
Ping on the issue.  It would be so much more useful if this feature were available.

**Comment by mehmetbektas** [comment]
Hello @mehmetkose and everyone,
I created send methods with example. The cahnges are in here: https://github.com/mehmetbektas/react-websocket/commit/bdeb15b7e7a0afac515f56e7550d0d89a6961cbe

And the pull request is here: https://github.com/mehmetkose/react-websocket/pull/26/files

Thanks.

**Comment by kongchengqiu** [comment]
Please merge this PR https://github.com/mehmetkose/react-websocket/pull/26/files

**Comment by mehmetkose** [comment]
Sorry guys I've been busy for a while. I didn't tested it but seems pretty clever

**Comment by divyanshu707** [comment]
I don't think that the build file in the above PR has been updated. It couldn't detect sendMessage fn for me.

**Comment by zhangrui95** [comment]
this.refWebSocket.sendMessage is not a function

**Comment by rajqumar** [comment]
send function is not working

**Comment by Ironjanowar** [comment]
Any news on this?

**Comment by mehmetkose** [comment]
alright, closing this
