### ISSUE TITLE
New Instance on every render() ?

### ISSUE THREAD

**Issue by tshradheya** [mehmetkose/react-websocket#42]
Does this mean that if I call `setState({})`, it will cause render and the Websocket tag will happen again making the socket start a new connection?

**Comment by Gerst20051** [comment]
I think I'm noticing this behavior as well. Did you come up with a solution? @tshradheya

**Comment by tshradheya** [comment]
I ended up using the websocket in native React native. It is also a bit buggy but it will allow you to have one instance for the entire app

**Comment by Gerst20051** [comment]
I also ended up implementing it directly. @tshradheya
